version: '3'
services:
  scylladb:
    image: scylladb/scylla:latest
    command: --smp 1 --overprovisioned 1 --developer-mode 1
    ports:
      - "9042:9042"
    volumes:
      - ./init.cql:/init.cql
    entrypoint:
      - /bin/sh
      - -c
      - |
        until cqlsh -f /init.cql; do
          echo "cqlsh failed, retrying in 5 secs..."
          sleep 5
        done &
        exec /docker-entrypoint.py --smp 1 --overprovisioned 1 --developer-mode 1
